services:
  udp2raw-client:
    image: udp2raw-docker
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    command: -l0.0.0.0:${LOCAL_PORT} -r${REMOTE_HOST} ${EXTRA_ARGS}
    cap_add:
      - NET_RAW

    ports:
    - ${LOCAL_PORT}:${LOCAL_PORT}/udp
